### ISSUE TITLE
Does not work on unmodified /system

### ISSUE THREAD

**Issue by sjennison** [nkming2/power-menu#14]
This app does not work on a system that is unmodified (such as the latest, recommended way to root Android N with SuperSu). It would be nice if features such as replacing the stock power menu could work without installing as a system app, since that's not possible while keeping the system `ro`.

**Comment by nkming2** [comment]
Currently it's necessary in order to gain the two signatureOrSystem permissions -- SHUTDOWN and REBOOT. Still worth exploring though, as it's also creating confusion on the installation and uninstallation process beside killing OTA

**Comment by sjennison** [comment]
Hmm. would it be possible to use a root shell to issue a shutdown command or something like that? That makes sense, I figured there was a reason you needed system access.
