### ISSUE TITLE
Would  you  please  publish  a  Java  version ???

### ISSUE THREAD

**Issue by SeekingForever** [nkming2/power-menu#22]
Hi ,I  am a  beginner  in  Android  development , I  really like  the  feature  in this application . 
But  I  am  not  familiar  with  Kotlin  language . So, I was  wondering  whether  you  can  publish  a  new  version  which  is  written  in  pure  Java  language  when  you  are  free. 
     My  English  is  very  poor , and  I  hope  you  can  understand  what  I  mean .
     Thank  you  very  much ! Have  a  nice  day  !

**Comment by nkming2** [comment]
Hi. No, it's probably not gonna to happen. However, this project was originally written in pure Java and was only later migrated. So you could browse the tree at that time [here](https://github.com/nkming2/power-menu/tree/8c1cef20401c2a2be5190dea328ace2bbca41d82). However be aware that it's quite old and thus lacking new features & bug fixes.
Cheers

**Comment by SeekingForever** [comment]
Thank you very much !
