### ISSUE TITLE
Cannot Uninstall

### ISSUE THREAD

**Issue by AdrianVovk** [nkming2/power-menu#6]
I cannot pre-uninstall this app.
It keeps giving me "Failed to _______. No root?" Even tough I have root for sure. 

I decided to uninstall and I can't even do that.

Would love to use this app especially if it would respond to power button clicks

**Comment by nkming2** [comment]
Would you mind sharing the logcat output?

**Comment by AdrianVovk** [comment]
It looks like my rom developer is missing some files (in fact, the whole /system/bin/sh directory)

Probably the issue
